name: Build and test everything
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      run:  python -m pip install --upgrade pip
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install 1
    - name: Build Owie
      run: pio run -e d1_mini_lite_clone
    - name: Run tests Owie
      run: pio test -e native
